#ifndef SM_DEMOSET_GLOBAL_H
#define SM_DEMOSET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SM_DEMOSET_LIBRARY)
#  define SM_DEMOSETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SM_DEMOSETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SM_DEMOSET_GLOBAL_H
